### ISSUE TITLE
Вопрос: Будем ли переводить новую документацию с Beta сайта?

### ISSUE THREAD

**Issue by KiraBurova** [reactjs/ru.react.dev#764]
Собственно вопрос в заголовке)
Хотелось бы вписаться в перевод новой документации, видимо для начала надо создать issue с чек листом отсюда https://github.com/reactjs/reactjs.org/issues/4135
Это планируется / этим можно заняться?

**Comment by ntishkevich** [comment]
Спасибо вам за этот ишью. Да, планируем. Для этого нужно будет мэйнттейнерам подать заявку, чтобы иметь два домена с актуально документацией и бета версией. Как только все необходимые подготовки будут сделаны, то в этой ишью сообщим дополнительно.

**Comment by fpetrakov** [comment]
> Спасибо вам за этот ишью. Да, планируем. Для этого нужно будет мэйнттейнерам подать заявку, чтобы иметь два домена с актуально документацией и бета версией. Как только все необходимые подготовки будут сделаны, то в этой ишью сообщим дополнительно.

Привет, бета теперь уже не бета (https://react.dev/blog/2023/03/16/introducing-react-dev), так что буду рад помочь с переводом, как только будут сделаны необходимые подготовки :)

**Comment by rkashigin** [comment]
+1, тоже хотел бы поучаствовать в переводе доки:)

**Comment by gaearon** [comment]
Мы перенесли старую доку в `legacy` бранч и обновили `main` к новой документации. Поправили домены тоже. Можно переводить.

**Comment by gaearon** [comment]
Организуемся тут: https://github.com/reactjs/ru.react.dev/issues/843
