### ISSUE TITLE
Перевод слов state и node

### ISSUE THREAD

**Issue by gcor** [reactjs/ru.react.dev#849]
@gaearon @ntishkevich  есть несколько вопросов про глоссарий, подскажите пожалуйста.

**state** — может быть использовать в этот раз слово "стейт", а не "состояние"? Кажется, формулировка "стейт" прижилась так же как и "пропсы". Как будто "стейт" это термин, а не просто какое-то "состояние".

**node** — узел? Но, кажется, редко так его называют. Интересный пример: 
_`<Fragment>`, often used via `<>...</>` syntax, lets you group elements without a **wrapper node**._
`<Fragment>`, часто используемый как `<>...</>`, позволяет группировать элементы без создания **дополнительного тега** (или ноды, узла-обёртки, элемента?)

**Comment by Hellnar** [comment]
Хороший вопрос по поводу **state**. 
В моем понимании, поскольку документация в первую очередь для начинающих (которые обычно приходят после JS и не работали со стейтом раньше), то перевод "состояние" будет для начинающих более понятным.
Но в то же время "props" уже есть в глоссарии как "пропс". Поэтому согласно такой структуре "state" я бы тоже добавил как "стейт".

По поводу **node** - интересно, что MDN часто [не переводят ноды](https://developer.mozilla.org/ru/docs/Web/API/Node), а оставляют слово на английском. 
Но во многих местах также встречаются определения "узел" или "коллекция узлов" (**nodeList**).
Поэтому для синхрона с MDN я думаю перевод "узел" - самый подходящий вариант.

В случае с переводом страницы Fragment я поддерживаю вариант "без создания дополнительного тега" (или элемента).

**Comment by ntishkevich** [comment]
Касаемо `state`, на мой взгляд, как переводили `состояние`, так и стоит продолжать. Это распостраненный термин применяемый в целом в компонентном подходе, например, `Open State` у `<details>` и веб-сервисы, которые также могут хранить состояние `stateful` и `stateless`.

Среди типов узлов DOM есть такой тип `DocumentFragment`, на мой взгляд, `Fragment` в React как раз схожи по смыслу с `DocumentFragment`. И ведь они явно не представлены какими-то тэгами в разметке, поэтому я бы придерживался перевода `узел`.

**Comment by gcor** [comment]
Если бы я объяснял простыми словами стейт, то я бы сказал — «стейт в реакте нужен для работы с состоянием». Сейчас как будто выходит «состояние в реакте нужен для работы с состоянием»

Также обычно говорят стейт-машина, а не состояние-машина

На хабре достаточно статей со словом стейт в контексте реакта [https://habr.com/ru/search/?q=стейст](https://habr.com/ru/search/?q=%D1%81%D1%82%D0%B5%D0%B9%D1%82)

**Comment by titovmx** [comment]
Поправьте, если не прав, но кажется стейт-машина по-русски - это конечный автомат. Слово "состояние" используется в любой литературе, связанной с теорией автоматов. Мне кажется, в нашем контексте смысл близкий и тащить англицизм не стоит.

**Comment by ntishkevich** [comment]
> Поправьте, если не прав, но кажется стейт-машина по-русски - это конечный автомат. Слово "состояние" используется в любой литературе, связанной с теорией автоматов. Мне кажется, в нашем контексте смысл близкий и тащить англицизм не стоит.

@titovmx Все так и про State Machine и про слово "состояние" как перевод `state`.

@gcor На хабре тоже хватает статей со словом "состояние", поэтому как аргумент не подходит. Во-первых, касаемо объяснения `state` простыми словами, я скажу, что объяснение надо начинать с того, что термин общий, как я ранее и писал.  Во-вторых, исходя из твоих предложений не переводить `state` как состояние и получаем - **Стейт нужен для работы стейтом** и это уже масло масленое.

**Comment by gcor** [comment]
> исходя из твоих предложений не переводить state как состояние и получаем - Стейт нужен в React для работы стейтом и это уже масло масленое

моё предложение — «стейт в реакте нужен для работы с состоянием», а не «состояние в реакте нужно для работы с состоянием»

_стейт_ это такой же термин как и _пропс_, а состояние это просто слово, такое же как и слова свойства.

Если мы ввели термин пропс, почему бы нам не ввести термин стейт )

Если в статьях есть разные варианты, интересно было бы узнать статистику как говорят в просторечии.

**Comment by ntishkevich** [comment]
> > исходя из твоих предложений не переводить state как состояние и получаем - Стейт нужен в React для работы стейтом и это уже масло масленое
> 
> 
> 
> @ntishkevich, моё предложение — «стейт в реакте нужен для работы с состоянием», а не «состояние в реакте нужно для работы с состоянием»
> 
> 
> 
> кажется, что _стейт_ это такой же термин как и _пропс_, а состояние это просто слово, такое же как и слово свойства.

Состояние этот как раз таки термин. Упомянутые тобою конечные автоматы имеют конечное множество состояний и здесь состояния не просто слово красивое, а конкретный термин с его значением,  к примеру, [взял ссылку с вики](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5_(%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0)?wprov=sfti1)

Как я уже в говорил неоднократно, состояние, а это тот же стейт, и термин выше тоже сюда относится, это так не только для React, например, State Management (управление состоянием), шаблон проектирования "Состояние" или Application State (состояние приложения).
