### ISSUE TITLE
Введение: знакомство с React

### ISSUE THREAD

**Issue by anatoliyfs** [reactjs/ru.react.dev#985]
Статья:
https://ru.legacy.reactjs.org/tutorial/tutorial.html#setup-for-the-tutorial
Все ссылки на примеры, код, на готовую игру битые.
Например:
https://codepen.io/gaearon/pen/gWWZgR?editors=0010

**Comment by titovmx** [comment]
привет!
к сожалению, старая версия документации больше не поддерживается, а перевода новой для туториала пока нет.
Ссылка на новую доку -  https://ru.react.dev/learn/tutorial-tic-tac-toe, там можете ознакомиться с примерами.
Если у вас будет желание поучаствовать в переводе, мы это приветствуем и готовы всячески помочь. Начать можно отсюда https://github.com/reactjs/ru.react.dev/issues/843.

**Comment by anatoliyfs** [comment]
Спасибо за ответ и ссылку, разберемся и на английском.
